<Window xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        Title="MainWindow"
        Foreground="#000"
        Height="285" Width="650" Margin="0"
        ShowInTaskbar="False"
        BorderThickness="0"
        Background="{x:Null}"
        WindowStartupLocation="CenterScreen"
        ScrollViewer.VerticalScrollBarVisibility="Disabled"
        HorizontalContentAlignment="Center"
        UseLayoutRounding="False"
        FontFamily="Courier New"
        AllowsTransparency="True"
        WindowStyle="None"
        KeyDown="handleclick"
        MouseDown="handleclick">
    <Window.Resources>
        <SolidColorBrush x:Key="AboutWindowTextColor" Color="#2c3e50"/>
        <SolidColorBrush x:Key="AboutWindowHightlightColor" Color="#f39c12"/>
        <Style TargetType="{x:Type TextBlock}">
            <Setter Property="Foreground"
                    Value="{StaticResource AboutWindowTextColor}"/>
        </Style>
        <Style TargetType="{x:Type Button}">
            <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
            <Setter Property="Background" Value="{StaticResource AboutWindowTextColor}"/>
            <Setter Property="BorderBrush" Value="#cccccc"/>
            <Setter Property="BorderThickness" Value="0"/>
            <Setter Property="Foreground" Value="White"/>
            <Setter Property="HorizontalContentAlignment" Value="Center"/>
            <Setter Property="VerticalContentAlignment" Value="Center"/>
            <Setter Property="Padding" Value="10,0,10,0"/>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="{x:Type Button}">
                        <Border Name="Chrome"
                                Background="{TemplateBinding Background}"
                                BorderBrush="{TemplateBinding BorderBrush}"
                                BorderThickness="{TemplateBinding BorderThickness}"
                                CornerRadius="10"
                                Margin="2"
                                Height="20"
                                SnapsToDevicePixels="true">
                            <ContentPresenter Name="Presenter"
                                                      Margin="{TemplateBinding Padding}"
                                                      VerticalAlignment="{TemplateBinding VerticalContentAlignment}"
                                                      HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                                      RecognizesAccessKey="True"
                                                      SnapsToDevicePixels="{TemplateBinding SnapsToDevicePixels}"/>
                        </Border>
                        <ControlTemplate.Triggers>
                            <Trigger Property="IsMouseOver" Value="True">
                                <Setter Property="Background" Value="{StaticResource AboutWindowHightlightColor}" />
                                <Setter Property="BorderBrush" Value="{StaticResource AboutWindowHightlightColor}" />
                                <Setter Property="Foreground" Value="White" />
                            </Trigger>
                        </ControlTemplate.Triggers>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style>
        <Canvas x:Key="pyRevitLogo">
            <Canvas.Resources>
                <LinearGradientBrush x:Key="LogoDarkGradient"
                                     MappingMode="Absolute"
                                     StartPoint="155,173"
                                     EndPoint="-4,113">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#2C3E50" Offset="0"/>
                            <GradientStop Color="#2C3E50" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoLightGradientA" MappingMode="Absolute" StartPoint="-9,107" EndPoint="126,116">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#F1C40F" Offset="0"/>
                            <GradientStop Color="#FFCF10" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoLightGradientB" MappingMode="Absolute" StartPoint="129,276" EndPoint="179,101">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#F1C40F" Offset="0"/>
                            <GradientStop Color="#FFCF10" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                    <LinearGradientBrush.Transform>
                        <MatrixTransform Matrix="0.8407 0.5416 -0.5416 0.8407 82.663 -38.4394"/>
                    </LinearGradientBrush.Transform>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoLightGradientC" MappingMode="Absolute" StartPoint="55,4" EndPoint="163,69">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#FFCF10" Offset="0"/>
                            <GradientStop Color="#F1C40F" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighLightGradientA" MappingMode="Absolute" StartPoint="139,130" EndPoint="31,60">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#00FFD633" Offset="0"/>
                            <GradientStop Color="#FFD633" Offset="0.9975"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighDarkGradientA" MappingMode="Absolute" StartPoint="135,167" EndPoint="-6,110">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#0034495E" Offset="0"/>
                            <GradientStop Color="#0B1014" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighDarkGradientB" MappingMode="Absolute" StartPoint="176,95" EndPoint="49,43">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#0034495E" Offset="0"/>
                            <GradientStop Color="#0B1014" Offset="1"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
                <LinearGradientBrush x:Key="LogoHighLightGradientB" MappingMode="Absolute" StartPoint="68,28" EndPoint="145,19">
                    <LinearGradientBrush.GradientStops>
                        <GradientStopCollection>
                            <GradientStop Color="#00FFD633" Offset="0"/>
                            <GradientStop Color="#FFD633" Offset="0.9975"/>
                        </GradientStopCollection>
                    </LinearGradientBrush.GradientStops>
                </LinearGradientBrush>
            </Canvas.Resources>
            <Polygon Points="0,140.3 121.8,218.4 172.9,161 22.3,65 "
                     Fill="{StaticResource LogoDarkGradient}"/>
            <Polygon Points="63,50.6 100,158.9 180.3,102.3 118.8,1 "
                     Fill="{StaticResource LogoDarkGradient}"/>
            <Polygon Points="21.5,65 181.5,102.3 100,158.9 -1,140.3 "
                     Fill="{StaticResource LogoLightGradientA}"/>
            <Polygon Points="122.4,166.2 198.1,132.8 121.8,219.5 "
                     Fill="{StaticResource LogoLightGradientB}"/>
            <Path Data="M185.7 58.8L118.8 0l-57 50.6l124.6 42.2L185.7 58.8z M150.3 64.8c-5.4 0-9.7-4.4-9.7-9.7  c0-5.4 4.4-9.7 9.7-9.7c5.4 0 9.7 4.4 9.7 9.7C160 60.5 155.6 64.8 150.3 64.8z"
                  Fill="{StaticResource LogoLightGradientC}"/>
            <Polygon Points="180.3,102.3 100,158.9 22.3,65 "
                     Fill="{StaticResource LogoHighLightGradientA}"/>
            <Polygon Points="0,140.3 0,140.3 109.3,187.1 137.3,138.3 133,135.6 100,158.9 "
                     Fill="{StaticResource LogoHighDarkGradientB}"/>
            <Polygon Points="61.8,50.6 167.7,96.1 168.5,86.7 "
                     Fill="{StaticResource LogoHighDarkGradientA}"/>
            <Polygon Points="155.1,31.8 118.8,0 61.8,50.6 "
                     Fill="{StaticResource LogoHighLightGradientB}"/>
        </Canvas>
    </Window.Resources>
    <Border BorderThickness="1"
            CornerRadius="15"
            BorderBrush="#ddd">
        <Border.Background>
            <SolidColorBrush Color="#fff"/>
        </Border.Background>
        <Grid Margin="20,20,20,20">
            <Grid.ColumnDefinitions>
                <ColumnDefinition Width="220"/>
                <ColumnDefinition Width="*"/>
            </Grid.ColumnDefinitions>
            <ContentControl Content="{StaticResource pyRevitLogo}"
                                Grid.Column="0"
                                Margin="10,10,0,0"
                                HorizontalAlignment="Left"
                                VerticalAlignment="Top">
                <ContentControl.LayoutTransform>
                    <ScaleTransform ScaleX="1"  ScaleY="1"/>
                </ContentControl.LayoutTransform>
            </ContentControl>
            <StackPanel Grid.Column="1"
                            VerticalAlignment="Center">
                <TextBlock x:Name="pyrevit_title"
                           VerticalAlignment="Top"
                           HorizontalAlignment="Center"
                           FontSize="44"
                           MouseDown="opengithubcommits">
                    <Run Text="pyRevit"/><Run x:Name="short_version_info"
                                              FontSize="20"
                                              Text=" vX.X"/>
                </TextBlock>
                <TextBlock x:Name="pyrevit_subtitle"
                           HorizontalAlignment="Center"
                           TextAlignment="Center"
                           TextWrapping="Wrap"
                           VerticalAlignment="Top"
                           FontSize="14"
                           LineHeight="20"/>
                <WrapPanel Margin="0,15,0,0"
                           HorizontalAlignment="Center">
                    <Button Content="Credits" FontSize="14"
                            Click="opencredits"/>
                    <Button Content="Docs" FontSize="14"
                            Click="opendocs"/>
                    <Button Content="Blog" FontSize="14"
                            Click="openblog"/>
                    <Button Content="Github" FontSize="14"
                            Click="opengithubrepopage"/>
                    <Button Content="YouTube" FontSize="14"
                            Click="openyoutubechannel"/>
                </WrapPanel>
                <WrapPanel HorizontalAlignment="Center">
                    <Button Content="Support" FontSize="14"
                            Click="opensupportpage"/>
                    <Button Content="Release Notes" FontSize="14"
                            Click="openreleasenotes"/>
                </WrapPanel>
                <TextBlock x:Name="coded_with_love"
                           Margin="0,10,0,0"
                           TextWrapping="Wrap"
                           VerticalAlignment="Bottom"
                           FontSize="14"
                           HorizontalAlignment="Center"
                           TextAlignment="Center">
                    <Run Text="&lt;/&gt; with"/>
                    <Run FontSize="17" Text="♥"/>
                    <Run x:Name="madein_tb"/>
                    <LineBreak/>
                    <TextBlock x:Name="copyright_tb"
                               MouseDown="openkeybaseprofile"/>
                </TextBlock>
            </StackPanel>
        </Grid>
    </Border>
</Window>
